site_name: Curve Docs
site_url: https://bout3fiddy.github.io/curve-mkdocs/
site_author: CurveFi

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

nav:
  - Stableswap Exchange:
    - Overview: stableswap_exchange/overview.md
    - Pools:
        - Overview: stableswap_exchange/pools/overview.md
        - Plain Pools: stableswap_exchange/pools/plain_pools.md
        - Lending Pools: stableswap_exchange/pools/lending_pools.md
        - Metapools: stableswap_exchange/pools/metapools.md
        - Admin Controls: stableswap_exchange/pools/admin_pool_settings.md
    - Liquidity Pool Tokens:
        - Overview: stableswap_exchange/lp_tokens/overview.md
        - Curve Token V1: stableswap_exchange/lp_tokens/curve_token_v1.md
        - Curve Token V2: stableswap_exchange/lp_tokens/curve_token_v2.md
        - Curve Token V3: stableswap_exchange/lp_tokens/curve_token_v3.md
    - Deposit Contracts:
        - Overview: stableswap_exchange/deposit_contracts/overview.md
        - Lending Pool Deposits: stableswap_exchange/deposit_contracts/lending_pool_deposits.md
        - Metapool Deposits: stableswap_exchange/deposit_contracts/metapool_deposits.md
    - Cross Asset Swaps:
        - Overview: stableswap_exchange/cross_asset_swaps/overview.md
        - SynthSwap: stableswap_exchange/cross_asset_swaps/synthswap_exchange.md
  - Cryptoswap Exchange:
      - Overview: cryptoswap_exchange/overview.md
  - Curve DAO:
      - Overview: curve_dao/overview.md
  - Registry:
      - Overview: registry/overview.md
  - Factory:
      - Overview: factory/overview.md
      - Deployer API: factory/deployer_api.md
      - Registry API: factory/registry_api.md

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/logo.png"
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - 'stylesheets/extra.css'

repo_name: bout3fiddy/curve-mkdocs # for example: 'lyz-code/pydo'
repo_url: https://github.com/bout3fiddy/curve-mkdocs.git # for example: 'https://github.com/lyz-code/pydo'
